---
title: "Spectral Instrument Comparison -- 2019"
author: "Ruby An"
date: "July 1, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

getwd()
## Required Packages
library("tidyverse")
library("knitr")
source("UnispecProtocol/unispec_protocol_functions.R") # file loads required functions

data_path <- "UnispecProtocol/spectral_instrument_comparison/"

band_defns <- tribble(
  ~definition, ~color, ~min, ~max,
  "ITEX", "red", 560, 600,
  "ITEX", "nir", 725, 1000,
  "MODIS", "red", 620, 670, 
  "MODIS", "nir", 841, 876,
  "MODIS", "blue", 459,479,
  "SKYE", "red", 620, 680,
  "SKYE", "nir", 830, 880,
  "SKYE", "blue", 455, 480,
  "Greenseeker", "red", 656, 656,
  "Greenseeker", "nir", 774, 774, 
  "RapidSCAN", "red", 670, 670,
  "RapidSCAN", "nir", 780, 780,
  "RapidSCAN", "red_edge", 730, 730, 
  "ToolikGIS_Drone_2018", "red", 640, 680,
  "ToolikGIS_Drone_2018", "nir", 820, 890,
  "ToolikGIS_MicaSense_2019", "blue", 455, 495,
  "ToolikGIS_MicaSense_2019", "green", 540, 580,
  "ToolikGIS_MicaSense_2019", "red", 658, 678,
  "ToolikGIS_MicaSense_2019", "red_edge", 707, 727,
  "ToolikGIS_MicaSense_2019", "near_ir", 800, 880,
  "ToolikEDC", "red", 560, 680,
  "ToolikEDC", "nir", 725, 1000
)


calculate_indices_comparison <- function(spectra, band_defns, instrument = "MODIS", indices = "NDVI") {
  # Calculates NDVI from dataframe including Spectra 
  ## inputs: spectra - Wavelength, Reflectance columns
  ##         band_defns : wavelengths definining colors 
  ##         instrument : e.g. MODIS, SKYE, ITEX
  ##         indicies   : the index to return 
  ## output: dataframe with Index : Value
  
  bands <- band_defns %>% 
    filter(definition == instrument) 
  
  blue <- bands %>% filter(color=="blue") %>% select(min, max) %>% as.numeric()
  nir <- bands %>% filter(color=="nir") %>% select(min, max) %>% as.numeric()
  red <- bands %>% filter(color=="red") %>% select(min, max) %>% as.numeric()
  
  spectra_bands <- spectra %>% 
    mutate(color = ifelse(Wavelength >= blue[1] & Wavelength <= blue[2], "blue",
                          ifelse(Wavelength >= red[1] & Wavelength <= red[2], "red",
                                 ifelse(Wavelength >= nir[1] & Wavelength <= nir[2], "nir",
                                        "other")))) %>% 
    group_by(color) %>% 
    summarize(Reflectance = mean(Reflectance))
  
  index_data <- spectra_bands %>%
    spread(color, Reflectance) %>% 
    mutate(NDVI = (nir-red)/(nir+red),
           EVI = 2.5*((nir-red)/(nir+6*red-7.5*blue + 1)),
           EVI2 = 2.5*((nir-red)/(nir+2.4*red + 1))) %>% 
    select_at(indices) %>% 
    gather(Index, Value, everything())
  
  return(index_data) 
}

)
```

## Read Filekeys & Data

```{r}

## Keys 
unispec_sc_filekey <- read_csv(paste0(data_path, "2019-06-26_NDVI-comparison_Unispec-SC_filekey.csv"))
unispec_dc_filekey <- read_csv(paste0(data_path, "2019-06-26_NDVI-comparison_Unispec-DC_filekey.csv")) 
asd_filekey <- read_csv(paste0(data_path, "2019-06-26_NDVI-comparison_Unispec-DC_filekey.csv"))


## Data

#### RapidSCAN & Greenseeker 
scanners <- read_csv(paste0(data_path, "2019-06-26_NDVI-comparison_RapidSCAN-Greenseeker_data.csv"))

#### Unispec-SC 
unispec_sc_data <- read_csv(paste0(data_path, "2019-06-26_NDVI-comparison_Unispec-SC_data.csv"), skip = 1, col_names = T) %>% 
  select(-X9) %>% # remove empty column
  rename(Height = `Instrument Height (m)`, FILENAME = `File Name`) %>% 
  gather(key = Wavelength, value = Reflectance, `310`:`1130`) ## METADATA
unispec_sc_spectra <- unispec_sc_data %>% group_by(FILENAME) %>% 
  nest(Wavelength, Reflectance, .key = Spectra) ## to join with filekey
  
unispec_sc_dataframe <- unispec_sc_filekey %>% full_join(unispec_sc_spectra) %>% 
    mutate(Indices = map(Spectra, function(x) calculate_indices(x, band_defns = band_defns, instrument = "MODIS", indices = c("NDVI", "EVI", "EVI2"))))

#### Unispec-DC
spu_files <- list.files(path = data_path, pattern = ".spu$", full.names = T, recursive=T)
spu_metadata <- map_dfr(spu_files, read_spu_file_metadata) %>% 
  mutate(spu_filename_full = spu_files)

spu_data <- spu_metadata %>% 
  mutate(Spectra=map(spu_filename_full, function(x) read_spu_file_spectra(x)))

unispec_dc_data <- spu_data %>% select(spu_filename, Site, FileNum, Date, DateTime, Integration_ms, Temp, Remarks, Spectra, everything()) ## METADATA

unispec_dc_spectra <- unispec_dc_data %>% select(spu_filename, Spectra) %>% 
  rename(FILENAME = spu_filename) %>% ## to join with filekey
  mutate(interpolated_spectra = map(Spectra, .f = interpolate_spectra))

unispec_dc_dataframe <- unispec_dc_filekey %>% full_join(unispec_dc_spectra) %>% 
  mutate(NOTES = as.character(NOTES)) %>% 
  

#### ASD
asd_spectra <- read_csv(paste0(data_path, "2019-06-26_NDVI-comparison_ASD_data.csv"), col_names = T) %>% 
  gather(2:94, key = FILENAME, value = Reflectance) %>% 
  rename(Wavelength = 1) %>% 
  group_by(FILENAME) %>% nest(Wavelength, Reflectance, .key = Spectra)

asd_dataframe <- asd_filekey %>% 
  full_join(asd_spectra)   %>%  mutate(NOTES = as.character(NOTES))


## Compiled Spectra 
asd_dataframe %>% 
  anti_join(unispec_sc_dataframe)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
